version: '3.4'

networks:
  iexec-net:
    external: true

services:

  chain:
    image: nexus.iex.ec/poco-chain:lv3.0.35-2
    container_name: chain
    ports:
      - 8545:8545
    networks:
      - iexec-net

  core-mongo:
    image: mongo:4-xenial
    container_name: core-mongo
    entrypoint: "/bin/bash"
    command: -c "mongod --bind_ip_all --port 27017"
    ports:
      - 27017:27017
    networks:
      - iexec-net

  core-mongo-ui:
    image: mongo-express:0.49
    container_name: core-mongo-ui
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=core-mongo
      # - VCAP_APP_PORT=8081
    ports:
      - 8082:8080
    networks:
      - iexec-net
    depends_on:
      - core-mongo

  ipfs:
    image: ipfs/go-ipfs:v0.4.20
    container_name: ipfs
    volumes:
      - /tmp/ipfs-docker-staging:/export
      - /tmp/ipfs-docker-data:/data/ipfs
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
    restart: on-failure
    networks:
      - iexec-net

  sms:
    image: nexus.iex.ec/sms:1.0.3
    container_name: sms
    environment:
      - HUB=0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC
      - GATEWAY=http://chain:8545
      - CAS=cas:8081
    ports:
      - 5000:5000
    networks:
      - iexec-net
    devices:
      - /dev/isgx
    depends_on:
      - chain

  iexec-sms:
    image: nexus.iex.ec/iexec-sms:0.0.1-SNAPSHOT-bd4543b
    container_name: iexec-sms
    environment:
      - HUB=0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC
      - GATEWAY=http://chain:8545
      - CAS=cas:8081
    ports:
      - 15000:15000
    networks:
      - iexec-net
    devices:
      - /dev/isgx
    depends_on:
      - chain

  cas:
    image: nexus.iex.ec/iexec-cas:0.0.2
    container_name: cas
    ports:
      - 18765:18765
      - 18767:8081
    networks:
      - iexec-net
    devices:
      - /dev/isgx

  sms-mongo:
    image: mongo:4-xenial
    container_name: sms-mongo
    entrypoint: "/bin/bash"
    command: -c "mongod --bind_ip_all --port 37017"
    ports:
      - 37017:37017
    networks:
      - iexec-net
    devices:
      - /dev/isgx

  sms-mongo-ui:
    image: mongo-express:0.49
    container_name: sms-mongo-ui
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=37017
      - ME_CONFIG_MONGODB_SERVER=sms-mongo
      # - VCAP_APP_PORT=8082
    ports:
      - 8083:8080
    networks:
      - iexec-net
    depends_on:
      - sms-mongo

  result-proxy:
    image: nexus.iex.ec/iexec-result-proxy:dev
    container_name: result-proxy
    environment:
      - IEXEC_PRIVATE_CHAIN_ADDRESS=http://chain:8545
      - IEXEC_PUBLIC_CHAIN_ADDRESS=http://chain:8545
      - MONGO_HOST=result-proxy-mongo
      - MONGO_PORT=47017
      - IEXEC_IPFS_HOST=ipfs
    ports:
      - 18092:18092
    networks:
      - iexec-net

  result-proxy-mongo:
    image: mongo:4-xenial
    container_name: result-proxy-mongo
    entrypoint: "/bin/bash"
    command: -c "mongod --bind_ip_all --port 47017"
    ports:
      - 47017:47017
    networks:
      - iexec-net

  result-proxy-mongo-ui:
    image: mongo-express:0.49
    container_name: result-proxy-mongo-ui
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=47017
      - ME_CONFIG_MONGODB_SERVER=result-proxy-mongo
      # - VCAP_APP_PORT=8081
    ports:
      - 8084:8080
    networks:
      - iexec-net
    depends_on:
      - core-mongo
