version: '3.4'

networks:
  default:
    external:
      name: iexec-scheduler_iexec-net

services:
  worker:
    image: iexechub/iexec-order-publisher:workerdrop
    restart: always
    container_name: order-publisher
    hostname: order-publisher
    environment:
      - DBUSER=xwuser
      - DBPASS=XXX
      - ADMINLOGIN=admin
      - ADMINPASSWORD=XXX
      - TRUST=30
      - PUBLISH_PERIOD=6
      - CATEGORY=5     
      - PRICE=10
