version: '3.4'

services:
  worker:
    image: iexechub/iexec-order-consumer
    restart: always
    container_name: order-consumer
    hostname: order-consumer
    environment:
      - CHAIN_NAME=rinkeby
      - CATEGORY=5
      - WORKERPOOL_OWNER=0x68ba0fC5E52e540778069113507507A012362cfD
      - PERIOD=60
    volumes:
      - ./sdk-env:/home/sdk-env

