version: '3.4'

networks:
  iexec-net:
    external: true
  iexec-worker-net:
    external: true

services:

  iexec-cas:
    image: nexus.iex.ec/iexec-cas:0.0.3
    #image: sconecuratedimages/iexec:cas-master
    container_name: iexec-cas
    #environment:
      #- RUST_LOG=debug
    ports:
      - 18765:18765
      - 18767:8081
    networks:
      - iexec-net
      - iexec-worker-net
    devices:
      - /dev/isgx

  iexec-las:
    image: nexus.iex.ec/iexec-las:sdk2.5
    container_name: iexec-las
    ports:
      - 18766:18766
    networks:
      - iexec-net
    devices:
      - /dev/isgx
