#!/bin/bash
# ./rmpool
echo "Stopping pool (stack-core-workers)..."

cd $(dirname $0)

./rmstack

./rmcore

./rmworkers

docker container rm -f $(docker container ls -aq)
echo "Removing iexec-net..."
docker network rm iexec-net > /dev/null 2>&1