#!/bin/bash
# ./uppool 5

BUILD=false
WORKERS=1

for i in "$@"
do
case $i in
    -b|--build)
    BUILD=true
    ;;

    -w=*|--workers=*|--nbworkers=*)
    WORKERS="${i#*=}"
    ;;

esac
done


cd $(dirname $0)

echo "Removing pool ..."
./rmpool

if [[ $BUILD == true ]]; then
	echo "Building core ..."
	./core/buildimage

	echo "Building worker ..."
	./worker/buildimage
fi

echo ""
echo "Starting pool (with $WORKERS workers)..."
./upstack #core stack
./upcore
./uptee #tee services

./upworkers $WORKERS

~/iexecdev/wallets/deploy --workerpool=yes
