#!/bin/bash
# ./uppool 5

nbWorker=$1

if [[ -z $nbWorker ]]; then
	nbWorker=1
fi

echo "Starting pool (with $nbWorker workers)..."

cd $(dirname $0)

./upstack

./upcore

~/iexecdev/wallets/deploy --workerpool=yes --app=docker.io/iexechub/vanityeth:1.1.1 --dataset=http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/512/iExec-RLC-RLC-icon.png

./upworkers $nbWorker

~/iexecdev/wallets/buy --workerpool=0xc0c288EC5242E7f53F6594DC7BADF417b69631Ba --app=0x63C8De22025a7A463acd6c89C50b27013eCa6472 --dataset=0x4b40D43da477bBcf69f5fd26467384355a1686d6



