#!/bin/bash
#./upworkers 5

nbWorker=$1

if [[ -z nbWorker ]]; then
	nbWorker=1
fi

echo "Starting workers (with $nbWorker workers)..."

cd $(dirname $0)

workerId=1
while [ "$workerId" -le "$nbWorker" ]; do
  ./upworker $workerId
  echo "Worker $workerId started"
  workerId=$(($workerId + 1))
done

