#!/bin/bash
# upworker 1 -b

cd $(dirname $0)

workerId=$1

for i in "$@"
do
case $i in
    -j*)
    launchWithJar=true
    shift
    ;;
    -b|--build)
    BUILD=true
    ;;
esac
done

if [[ $BUILD == true ]]; then
    echo "Building worker ..."
    ./worker/buildimage
fi


if [[ $launchWithJar == true ]]; then
    echo "Starting worker$workerId ... (jar)"
    gnome-terminal --tab -- bash -c "./worker/upworkerjar $workerId; read line"
    exit 0
fi

#if [[ $launchWithDocker == true ]]; then fi
./rmworker $workerId
echo "Starting worker$workerId ... (docker)"
# gnome-terminal --tab --title="Worker$workerId" -- bash -c "./worker/upworkerdocker $workerId; read line"
./worker/upworkerdocker $workerId
exit 0
