{
 "title": "Join Worker Pool",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<input type=\"button\" value=\"Go Home\" onclick=\"location.href='/d/Home/home'\" class=\"navbar-button\"/>\n<div class=\"text-center dashboard-header\">\n  <span>Join Worker Pool</span>\n</div>"
  },
  {
   "title": "Joined Us",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM hosts\n",
     "target": "db.worker.aggregate( [ \n    { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } },\n    { \"$project\": { \"value\": \"$count\",\"_id\": 0}}\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "Active Now",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM hosts\nWHERE (unix_timestamp(now())-unix_timestamp(lastalive) < 900) \n",
     "target": "db.worker.aggregate( [ \n    { \"$project\": {\n       \"Delay\": { \"$toInt\": { \"$divide\" : [ { \"$subtract\":  [\"$now\", \"$lastAliveDate\"]} , 1000 ]}}\n    }},\n    {\"$match\":{\"Delay\": {\"$lt\": 90000}}},\n    { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } },\n    { \"$project\": { \"value\": \"$count\",\"_id\": 0}}\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily Activity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "db.worker.aggregate( [ \n    { \"$project\": {\n       \"Delay\": { \"$toInt\": { \"$divide\" : [ { \"$subtract\":  [\"$now\", \"$lastAliveDate\"]} , 1000 ]}}\n    }},\n    {\"$match\":{\"Delay\": {\"$lt\": 90000}}},\n    { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } },\n    { \"$project\": { \"value\": \"$count\",\"_id\": 0}}\n] )\n",
     "target": "db.worker.aggregate( [ \n    { \"$project\": {\n       \"Delay\": { \"$toInt\": { \"$divide\" : [ { \"$subtract\":  [\"$now\", \"$lastAliveDate\"]} , 1000 ]}}\n    }},\n    {\"$match\":{\"Delay\": {\"$lt\": 86400}}},\n    { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } },\n    { \"$project\": { \"value\": \"$count\",\"_id\": 0}}\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "Ubuntu, CentOS or MacOS",
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 3 },
   "content": "<script>\n  var path = location.protocol+'//'+location.hostname+(location.port ? ':'+location.port: '');\n  document.getElementById('scriptLink').setAttribute('href', path+'/public/launch-worker.sh');\n  document.getElementById('inputLink').setAttribute('value', \"curl -fsSL --insecure \"+path+'/public/launch-worker.sh -o launch-iexec-worker.sh && bash ./launch-iexec-worker.sh');\n</script>\n\n<h2> Requirements </h2>\n<ul>\n<li>Docker CE\n<li>BC and WC packages installed\n<li> User that launches the script need to be able to launch docker commands\n</ul>\n<br />\n<h2> Start Worker </h2>\n\n<h4> Method 1 </h4>\n<ul>\n<li>Download <a href=\"#\" id=\"scriptLink\" target=\"_blank\" download>Launch Worker Script</a>\n<li>Launch it with \"bash ./launch-worker.sh\"\n</ul>\n\n<h4> Method 2 </h4>\nJust Launch: \n<input id=\"inputLink\" type=\"text\" data-share-panel-url class=\"gf-form-input\" ng-model=\"shareUrl\" value=\"\"></input>\n"
  },
  {
   "title": "Dapp Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.task.aggregate( [ \n    { \"$match\": { \"currentStatus\": \"COMPLETED\"}},\n    { \"$group\": { \"_id\": \"$dappName\", \"count\": { \"$sum\": 1 } } },\n   { \"$group\" : { \"_id\" : null, \"count\" : { \"$sum\" : 1 } } },\n    { \"$project\": { \"value\": \"$count\", \"_id\": 0}}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.task.aggregate( [ \n    { \"$match\": { \"currentStatus\": \"COMPLETED\"}},\n    { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } },\n    { \"$project\": { \"value\": \"$count\", \"_id\": 0}}\n\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM hosts\nWHERE runningJobs!=0\n",
     "target": "db.task.aggregate( [ \n    { \"$match\": { \"currentStatus\": {\n            \"$nin\": [\"INITIALIZE_FAILED\",\"REOPEN_FAILED\",\"FINALIZE_FAILED\",\"ERROR\",\"COMPLETED\"]\n    }}},\n    { \"$group\": { \"_id\": null, \"count\": { \"$sum\": 1 } } },\n    { \"$project\": { \"value\": \"$count\", \"_id\": 0}}\n\n])",
     "type": "table"
    }
   ]
  }
 ]
}